
services:
  web:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: emmi_db
    volumes:
      - postgres_emmi_data:/var/lib/postgresql/data/
    networks:
      - default
      - dokploy-network
    restart: always
    environment:
      POSTGRES_DB: emmi_db
      POSTGRES_USER: ebyted
      POSTGRES_PASSWORD: arkano
