# Generated by Django 5.1.6 on 2025-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='origen',
            field=models.CharField(default='index', max_length=50),
        ),
    ]
